server:
  port: 81

# 开启服务降级功能
feign:
  circuitbreaker:
    enabled: true
#  Eureka配置
eureka:
  client:
    # 不向eureka注册
    register-with-eureka: false
    service-url:
      defaultZone:  http://eureka7001.com:7001/eureka/, http://eureka7002.com:7002/eureka/, http://eureka7003.com:7003/eureka/


