server:
  port: 3344
spring:
  application:
    name: springcloud-config-server
  # 连接远程仓库
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ajiesw/spring-cloud-study.git
          default-label: main
          skip-ssl-validation: true
          username: ****
          password: ****
      # 读取分支
      label: main
